### ISSUE TITLE
PHP7 Kompatibilität

### ISSUE THREAD

**Issue by BugBuster1701** [Craffft/contao-imagesortwizard#3]
In der Datei widgets/ImageSortWizard.php sind in Zeile 78 und 192 noch `\String::` in Verwendung statt `\StringUtil::`

**Comment by BugBuster1701** [comment]
Dadurch funktioniert contao-photoalbums2 nicht mehr, wegen der Abhängigkeit.

**Comment by iCodr8** [comment]
In der Contao 4 Version muss es funktionieren. Contao 3.5 hat für Photoalbums2 keinen PHP7 Support.

**Comment by Luminanz** [comment]
In der Version 1.6.0 (aktuelle Version für contao 3.5) wird aber PHP-Support versprochen:
<img width="681" alt="bildschirmfoto 2017-10-25 um 16 51 52" src="https://user-images.githubusercontent.com/1551887/32005586-f50d61e0-b9a4-11e7-9b13-7280b245c0e0.png">

**Comment by iCodr8** [comment]
Oh, stimmt. Hab gedacht wir haben ein imagesortwizard-bundle, welches nur für Contao 4 ist.

**Comment by iCodr8** [comment]
Done.

> https://github.com/Craffft/contao-imagesortwizard/releases/tag/2.3.1
